import java.util.List;

public class Day4Part2 {

    public static void main(String[] args) {

        /*final List<String> input = List.of(
                "MMMSXXMASM",
                "MSAMXMSMSA",
                "AMXSXMAAMM",
                "MSAMASMSMX",
                "XMASAMXAMM",
                "XXAMMXXAMA",
                "SMSMSASXSS",
                "SAXAMASAAA",
                "MAMMMXMMMM",
                "MXMXAXMASX"
        );*/

        final List<String> input = List.of(
                "SSSXSSMSXMMAXXAXMSSMSSMSXMASXXMXMMXMSXSMXMMSASXMMAMMMMMXSAXMAMASMASASXSXMMMSMAXMSAMXAAXXXAMXSAMSAAMMXASXMXXXXASXMMSMMMMMMMSMMSAMSSSMXSMMXSXM",
                "MXMAMMMSAAMSSSXSMMMMMAMMMXMMXXAAXMAMMAASMSXMASAXSXMAAXAAAMAMXSXXMASMMAMXMAAAXXMASXSSMXAMSXMAMXXSMXXAMXXAXMSMMMMAAAXXAAAXAAAAXSAMMASXAMXXAMAS",
                "XAMAMSAMMMMAAMAAXAAMSAMXSAAXSSSMSSSSMXMAXMAMSMXMAASXMSMMSXMMXAMXMASXMAXAMMXSSMAMSAMXAXMMAMXXXXXMASXMMASXMAAXAASXMASXSSSSMSXSMXAMMMMMMSSMMSAM",
                "SXSASMMSXAMMSMMMSSSMSXSASMSXMAMAAXAAASXMASAMXASMSMMAMSMXXASMMSMXMASMSSMMXSAAMASXMMMASMXMAXMSASXMAMMMSXMASMMSSXSXXXMAMAMMAMAMASMMMMAAAAXAAXXS",
                "MXMXMAXXMXXAAAXAAAAAXAMAMAMMMAMMMMSMMMASXMASMXMAXXSAMMMMSMMAAAAAMMXAAAASAMMSMAMASXMAMMXSSSMXMSAAAXAMXAXAMXMAXMMMXSMAMAMMAMMMXMMAASMSSMSMMMMA",
                "MASMSMMMSMMSXMMXMMMMMMMSMAMSMXSAMXAXXSXMAMXXXXMXMMXMXSAAXXXMMSSXSAMSMSMMASAXMASXMAMMXSAMXAXXXSXMMSSSSSMXSXMASXMMAMSSSXSMMSASXAXSMMXAMXMAAASM",
                "SAXXAMAAAAMAASXMSXAXXSAMSSMMMMSAMXXMASXMAMSXMMSSMMSAASMMSMMSAMMAMMMXAMXSAMMSSXMASMMXAMASXMMMMMAMXXAAAMAMSXMMMMMMAMAXMAMAMSASXSMMASAMXAXXXXMX",
                "MXSSMSMSXSMMXMAAXXAMAMAXAXAASAMXMXMAXXMMAMSAMASAAAMMMSXMAMAMASMXMSMMXMAMXSAMXMSAMASMASAMAAAAASAMXMMMMMSMSASAXAASMMSXMAMAMMAMAXXMAMXSSMSMSSSX",
                "XMAAASMMAMAMSSMMMMSSXSMMMXMMSXXMSMMMSMAMSMSAMSSMMMSMMSXMXMMXXMMXAASMAMAMAMMMMMMXSAMAXMMMAMXSXXAXSMMXSXAAXAMASMMAAXAASASAMXAMMMSMAXAXAAAAAAAM",
                "MASMMMAXAXAMXMASXXAAMMAAXMAMXXXAAAAAAXMXMASAMXMAMXSAMXASAMXMMASMSXMMXMAMMMXMAMSMAMSMSAMXSAMXMMSXAXMMMSMMMMMXMAASMMXXMAMMSSXSAASASASXMMMMMSMA",
                "AMAMXSAMXSSMMXMMMMMSSSSMSAMSASMSMSMSSSXSMAMMXSXXMAXAXSXMXXMASAXXMMSXXSASMSSSMMXAMMSXMXMAXAMXAAMXAMXAMASAAXXXAXMAXSXSMAMXAMASMAMAMAMXMMXMAXAS",
                "SSXSXMXMXSXAMXSAAMXMMAAXAXXMAMAMXMMXAXAXMXSMAMMAMSMSMMMMXSMMMAMXMASAAXAMAAAXMASMXMSAMSMMMAMMMMMAMXXMMAXMMMSMSMSXAXAMMMSMASAXMAXAMXMAXSAMSSMX",
                "XMAMMSAMMSSSMAMMSMAMMSMMMMXMXMMMASXMXMXMAMAMMSMSXASAAAAMMMASMMMAXSMMMSSMMMSMSAXMASMAMAAXSSMXMASMMSSXMMSSMMSAAAXMMMAMAAAMXMMSXMXMXXSAXSMMMSAX",
                "MMSMAXASMXAMMXMAMMAMXAMMXMXSAAASASAXMASAMSSSMSAXMXSMSMXSASAMAASMMMAMXAXMAMXAMMMMXMMAMMMAMMAMXASAAAMASAAMAAMSMSMMXMASMSXSXAMXMMASMMMXXXXAAMMM",
                "XAASMSMMMMAMAAMASXMSMSAMAMMXXSXMASMMMSASAAAAAMMMMAMXMAAXMMAMMMSXAXSMMXXMMAMXAXSASASXSXMASMXMMMSMMMSAMMSSMMMXMAMMAMMSMMXAMXMAMSASAMAXXMSMSMXA",
                "MXMSXAMSXXXMSXSASAXMAXMSASXMMMXMXMMAMAAMMMSMMMXSMXSAMMMMSMXSAMXXSXMASASXSXSXAASAXASAAXSASXSXMAXAAXMXSXMAMSASMMMSASMSASXMSSSMMAAXMMMSAAXAAXMX",
                "SMMXMAMAMSAMXXMASMMMAMXSASMAMAXMAMMSSMXMAMXMXMXMAXMXXSAMXAASXXMAXXSAMMAAMAMMAMMMMMMMMMMMSMXAMSXSMXMMXASAMXMXAAASMSAMXMAMAAAXMMMMXMAXMMMMMMSA",
                "SAMAMSMMAAASXMMAMXAXAXMMMMMSMAXMAMAXAXMSAMXMASXMSMXMASXSMMMSASASXAMASXMSMAMMXMAXAXXXXASXSAMSMMAMAASXMXMAMMXSSMMXAMAMMMMMMXMMMAMMAMSSSMSAAAMX",
                "SAMMMAASMMMMMAMSSMSSSSMSSMSXMAMSAMMSSMMXAXAMASAXXAAXXMMMXAMXAMAMMAMAXAXXXSMMASMMSXMXMSMAMAMXASAMSMMAXSSMMMMMXASMMMASAAMXSAAXMAMXAMAAMASMSXXS",
                "MAMXSSXMSMSAMXMAAMMAMXAAAXSAMXMMAMXAMXAXSSSMSSXMMSMSMAASXSSMAMAMASMMMSMMMMASASAMXAAAMAMMMAMMAMSMXMMSMAAXSAXXMASAMSMSMMSAXSXMMASXSMMSMAMAXMXS",
                "SMMMXMAAAXSASMMSSMMAMMMMSXSXMAMSAMMAMMMMXAXXXMAMAAMXMSMSAMXMASASMXAAAMMSASMMAMAMSXXXSASXMAXMXMASXXAAMSMMSMSMSMMAMXASAMMMMXMAMMSAAMMAMXSAXAMX",
                "AASXAMMSMXSXMAAAMXSSMMSAMASMSSXMMSSSMSXSMMMXMMAMMXMAMXAMXMAXXXASXXAMXSASXSASXSSMMMSMAASXSASMMMAMMMSSMXAAXXAMAASMMMXMAMAXAMAXSMMXMMSASMMMXSAA",
                "SXMXXMAAMASMSMMMSAAAMASAMMMXAMASXMAXAAMXAXAASMSXSAMSSMMMSXSSSMAMMSMMXMAMAMXMAAXAXAAAMMMMMAXAAMASAAMAAMMMSSXSSMMAXMASXMMMSMMAAXMAXMSASXAAMMSS",
                "MASMMMSXSXSAXXXXMMSSMAXAXSXMMSAMAMSMMMMXMMSMSAAAXAMAXAXAXAXAMMSMAAMMAMAMSMMMXMSMMMSXXMAXXASXSMASMSSMMSXAAXXAMXSXMAMXMAMAAAMXXMSXSMMMMXMXSXMX",
                "XAMXSAMXAAMMXXAAXMAMMMSSMMMSAMAXAMXAXASAXAMAMMMSMXMMSSMSSMMAAXMMMSXSASAAAAMSMXMASXMXSSMSMXSAAMAXXAAXAAMMSSXMAXMMMXSMMAMSSXSMAAXXAXAXMAMSMAMM",
                "MSXMMASAMXMAAMSMMMAMSAMXAAAMXSMMSSMXSASMMMMAMSAMXMSXMAAAAXSAMSMSAMMMXMMSSSMASMMASAMAXAMXMAMMMMSXMSMMMSASAMXMAMXAMXSASAXMMAAXMMSAMMSSSMSASAMA",
                "XMASXMMMAMXMMXAAXMAXSXXSXMMSAMXAXAXAMMMXAAMAMMMMAMXASXSSSMSAXAAMASXSASMAAAXMSXMASAMXSAMXMMSXMAXMAMAMXAMMASXSASMXSASAMXSAMAMXMAXMXAMAMXXMMMXS",
                "ASXMASAXSMMSMSSXMMMXMMMSXSASMSMSMMMXSAXSXSSMSAMSAMXXMAMAAASASMSMMMASASMSSMMXSAMXSAAMXMAXMXSASAMXASXMSXSXMAASAMAXMAXXMASAMMXMMXSXMXSAMSMSMSAX",
                "MXASAMASXAAMMAAXSASAMXXSAMASASAMAASASMMMSMAAMAMSMMSXMAMAMXMXSMMXAMXMSMMAAXAXSASAXXMXAMMXMASAMXSMXSAAAMXMSMAMMMMMMSMMMXSMXSAAXMMAMXMAMMAAAMAS",
                "SSMMXMXAMMMSMMSMSASXXSMMAMMMMMAMSMMASXXMAMMMMMMMMMAAXMASXXSASASAMXXMXMMMSMSASAMXSAXMASAAMASXSXMXAXMMMXAXXXMSASMSAXAXMAMXAXMSMXSAMAXMAMXMSMAM",
                "XAMAMSSSXMAMAAXAMXMMMSASMMMSXMXMXAMSMAMMXXAXXAAXMASMMMAMMMMASAMXMMMSASAMXAXMMAMSAMXMAMXSMMSXMASMMXXXXMMSXSAMXXAMASXMMSSMMXMAMXMASASXSSSMMMAS",
                "MXMAXAAMXMASXMMSMMAXAMXAAMXMASMXSAMMMSMMAMSSMSSSMXMASMAXSAMAMXMAXXAMMSASMXMXMMMXMASMASXMXXSASXMAMASXXAAXMASXMMMMMMMMAAAAAAMMSXSAMASAMXAAXSSS",
                "MSSSMMSMXSXSAAAAMXMMMXMMMMAXXMMASAMXAAAMAXAAAAAAAXSMASXXSASAMSSXMMMSASAMMSXSASMXAMXSASAASMMMSAMSAASASMMXSAASAAXAAAXMMSSMSMSASMMXSAMMMSSMMMAM",
                "MMAAMXXAMXAMMAMXMASASASAXSSMSAMASMSMSSSMMMSSMMSMMAMXMAMASXMXMAMMAAMMMMXMSAASAMAMSAXMSSMMMXAAXAMAMXSXSAMAMXXXMMXSSSXSAMXAAXMAMAMASAMXAAXMASAM",
                "ASMMMXMAXMAMXXSXMASASAXXMXAASAMASAMAAAAXMAXAAAXMMMSAXAMMMSMXMASXMXMAMMMMMXMMAMAXMASMAXMSXSMSSSMAMXMASAMASXMSXSAMAMXASXMMMXSXSAMXXAMMMSSSMSAS",
                "MMAXSXMXSSMSSXSASMMMMMMSMMMXMMMXMAMXMSMMMSSMMMMXAAMMXMXAAXMASASXASXMMASXMMSMXMMMAAMMASMXAXAAXAXAMXSASMSAXAMAASXMSMSSXMXXAAMASXSXSSMSXMAAASXM",
                "XSMMMASAMAAAAAMAMAAXMAMXASXMAXSASMMSXMASAMAMSSSSMSXXAXXMSSMMMAMMXMAXMMXAAAMXSASMMMSAASAMXMMMSMSSSXMASAMXSSMMMMAAAAXXXSMMMSMAMAMXAASMAMSMMSAX",
                "MMMXXAMXSMMMMMMSMMASXMMSXMAMAMXAMXAAASAMXXAMAAAXSAMSMSAMAMAMSSMSXMAMSSSSMMSASAMAASAMXXMAMXAXXXAAXMMAMAMAAXXXAMMSMMMMMAAXAXMXMAMMMMMXXMXMSXMS",
                "AAMAMSSMMMMSXXXXAXASXSASMSMMXSMMMMASXMSMXMSMMSMMMXXAASXMAXAMXAASAXMASAAXMXMAMAMSMSMSSSXSASMAAMMSSSMSSXMMSSMSMXXAXAAAMMSMMXMAMMSMSMSSXMAXXAXX",
                "XAMAXMAAXMASAMMSXMMSAMASAAXXAAAASXAXMAXXMAMAAMAMSMMMMMXSSSXSSMMMAMASXMXMSMMSSSMXASXAAXAMASMXMMAAXAAAAAXAAMXAMMSMSMSMSAMASASAMXAAAAMMMSSSSMMM",
                "SSSSSXSMMMAMMAAAAXAMXMSMXMSMMSSMSMXSMAMMMMXMMSAMXXAXAMMMXAMXMAMXAMXMXAMMAAXAAAXMAMMXSMSMAMASXSXSSMMSSSMMMSSMSAXASMXAMAMAMXSXSSMMMSMXAMMAXAAX",
                "AAAASAAMMMSSXSASXXMXMXXAXMXAAMXMXXMSMAMXAAMSASXSMSASASAMXMMXSAMSSSXSMSMSSSMMSMMMMSAMAAXMAMXMASXMXMMMAXXAXXMXMXSAMMMSMMMSMMXMAXSASAMMSSMAXSXS",
                "SMMAMMMSAAXMAXAMAMXASAMMMMSSMSMXXMAXMSMXMXXMASASAMASXMXMASAAMXXSAMXXXAAAAAXAAAAAAAXAMMMASMXMXMMSAAAMMMSMMXMXAAMMMXAAXMAMASMMAMMXSASAAAMMMMSM",
                "XXMXSXAXMMXSAMMMAXSAMAAMAMMAAAAXSXMMAMASXSMMAMAMSMAMAMSSMSAMMMMMMXMAXMMMXMMSSSMMSSMMSXSAMMAMASASXMXMXMAMMSSMSAMXAMMSXSAMSMAMSSSXMXMMSXMMAXMX",
                "MXSASMMMSAAMXXXSXMMSSXMASXSAMMMMMAMSAMXMAAXSXMXMXMASMXXAMXAXXAAAMASMSSXSAMXXXMXXMXXXSAMASMASAMXXMSSSMSXSAAAMAAXMASMAAMXMMSSMAAAAXSMMAXMSMSSS",
                "SAMXXAXAMMXMXAMXXXAAMMMMAMXAXMXAMXMMAMAMSMMXMMASASMSXMSAMSXMSSSMSASAAAAXXMXMASXXMAMXMAMXMXASXSMSMAAAAAAMMSMMSMMMAAMMMMMAMAXMMSMSMSAMAMXAAAAX",
                "MASMSSMMSSMMSMSAMMMSSSSSSMSMMMSSSSXSAMXMMXMAAXAMXSXMAMSMMXAMMAAAMXMMMMMMXSASXMSAMSMXSMMXSMMSAMXAMMMMMMSMMAXMAAMSAMXMXAAXMAXSMMAAASAMAMMMMMSM",
                "MASXAAXXAAAMAAAAMAXXAXAAXMAXAMXAXAASXSSXXASMSMMSMXMMSMMSMSSMMMMMSXSSXXMAMMAMAMSXMASAAAMMMSXSMMSMSXXXAMXXSXSSSXMMMMAMXMSXMAXXAMSMMXXMXMAXAAXA",
                "MASMXSMMMSMMMMMMXXSMMMMMMSXSSSMXMMMXMAXASMMAAAAAMXXAAAXXMAMMAASASAAAXXASMMSMMXSXMAMSSMMSAXMXAASAMASAAMSAMXXXMAAXAXASASAMMSMSAMMXXXXMASMSMSSM",
                "MASXAXAMAXAMXMMMMMMXAAXAAXMAMAMXXXMASAMMMAAMMASMMSMASMMMMSSMSXMASMMMMMXMXAMAXXMAAAMXXAAMASMMMMSAMAMSSMMAXMXASXMSSSXSMMASMAMMAMXAXSMMMAMAMXAX",
                "SAMXXSAMASAMMMSAAXMASASMSXMMSMMMSMMAMAMXSXMXXXMXAASAAMSAXAAXXXMMMXAAAAAMMMSXMASXMMSASMMMMAAXAAXXMXMAXAMSAMMMAAMAXXMMXMSMMASXMMMMMSAAMASAMSAM",
                "XAMAMMAMMMAMXASXSMXAXMSXXASAMAASAMMSMXMAXXMSXXAMMMSSMAXXMSSMSSSMMSSSSMXMAMAXSXMXAXMMMMSSSMXSMSMXMAMASXMXAXAMXAMASMXMAXMASXSAXSASASXMSMSMAMMM",
                "SSSMMMSMSXSAMXMMXMMASAMASXMAMXMXASXAASMMSAASMMXMMAMAXMSSMAXAAXAXXXAAAXAASMMMMAXMMMMMMAAXAXAXAAXAMMSMXMASMSMSMSSXSAASMSSMMSMMMSAMASMAAAMAMXSX",
                "AMAAMSMAMMMMSSMMAMMMMAMAMMSSMSMSMMMMXSAMXMXXXXAAMSSMMXAXSAMMMSMMAMSMMAMXMASXXMSXMAXAMXSSMMSSSMSSXXAMAXMMAMASAAXAXXXSXAAMSXSAAMAMMMASMSSSXMAS",
                "MSSMMAMAMAXAAAAMXSASMXMASMAMAAAAXAXXAMAMXXMAXMXMXMAXSMMMSXSXXAXMMMAAXMXMSXMAAXMASMSMMAMAAAAXAAAAMSASXSMMXMAMMMMXMXXMMSMMAASMXXAMXAXXAAAAXSSX",
                "XAMXXXXAMSMMSSXMMSASXXXXXMASMMSMSSSMXSAMMAAXSMSXMMMMAAXXXAMASXSAXSMSMXAAXSXSMMSAMXAAMSSSMMSMMMMSMMMMASAAAMXSAAMMMMMMMMAAMMMAMSMSSSSMMMMSAMXS",
                "MMSMSSSMSAAMAXAMXMMMMMMMAMASAAXAAAMAMSMSXSSXAAAASAMXSMMMMSMXMASMXMXMAXMXAMMASAAAMSSSMAAASXMMSAAMMAAMXMASXSASXMSAMAAAMXXMSAMAMAAAAASXMXAMMSAX",
                "AXMAAAAMSMSMSSSMSASAAAXAAMSSMMMMMSMAMMAMAMMXMMMXMASAMAAXAAMAMXMXAMSSSSXMAMSAMXXAMAAXMMSMMSXASMSSSXMMAXXMAAMMMXXAMMSMSAXMSASXMMSMMMMMMMXSXMAS",
                "SMMMMSAMMAXAAAAAXASXSSMSXSAMXSAAAAMMXSAMAMSAMASMSMMMSSMSSSMMSASXSAAAMAASAMMASMSSMMSMXXMMAMMMMMMMAASXMMAMXMMSSMSSMMXMAXSASAMMXXAMXMASAMMMAMMM",
                "MXSAMMXSMMMMMMMMMXMAXAMXMMMMMMMXSMMXAXASXMMASASAAMAAMAAXXMASMXMAMMMSMSMMAMSXSAAAXXAAMMAMSSXAAXAMMMMASXAMASAMXAAAMMAXAAMAMXAMMSASXMASASASASAS",
                "SASMSXAMASAMAXAAMMMMSMMXMAAAAXXMMXSXASMMXSSMMMMXMSMMMMXMMMXMAAMSMXAMXMAXAXMAMMMSASXSXSAMAMMASXMSMMMAMSMMMMMXMMMSSSSMMSMXMMXSXSMMXMMSXMASASAS",
                "MAMAMMMSASASMXSAMXAAAAAMSSSSSXSAAAMMMMAAAMMMASMXMMMSAMXMXMAMSMSAXMMSAMSSSSMAMAXMASAAASAMAMXMAMXAAAMXMAXAXAAAMAAAXMAAXAAAXXAMAXXAAMASAMAMAMAM",
                "MAMAMAMMMSMMMMAMXMMMXSMAXMAAAASMMASAXSMMMSMSASAMXAASAMXMSSXXAXXMAXXMASXAAMMMXMSMXMMMMMMSSSSXSMSXMMMXSMSSMMSXSAMXSSSMMSSMMMAMAXMSMSASXMSMSMSM",
                "SMSSSMSAMMMAXSSSSMXSXXXMAMMMMMMMSAXAMMAAAXXMASASMMMSAXAMMAMSXMAMSMSSMMMMMMAXASAMXXMMXSAAXXMAXASMSXXMAMAMAMXMAMMXAXAMXMMAXXSMMXXAAMMMAAMAMAAA",
                "AAAXAXSAMAMMXMAAAXAXMAMSSMMMXMMMMXXSASXMMSAMXSXMAAXSXSSSMAMMMSMAAAMMMAXXASMSMXASMMSMAMMMMMAMMAMASAASAMASMMXMAMMXMSAMXSMXMAMAASXSSMMSMMMAMSMS",
                "MMMSMMSXMSSMAMMMMMMSMMMXAAAXAAAASMXMASAAMXASAMXSSMXXMAXXXASAMAMSMMMXSAMMXMMAXSMMMAAMMSMSASAXMSMAMXMMASAMXAASASXAXAAMMSAAMAMMMSAAXXAAAXSMMMAM",
                "MSAMXASAMXAMSMSAXAAAAAXSMMMSASMXSAAMASMMMXAMXSAMASXMXSXMMXSMSXXMMMSAMXSMAXSAMMAAMSSSXAAMMMSMSXMSSMMSAMXSMSXSAXMASMSMAXMXMXSXSMMMMMSSSMXSAMXM",
                "XAAAMMXMMSXMXASASMXSSMMAAXXAXXXAMXMMXMMXSAMXMAXSAMXMMMAASMSAMMMAAXMASAAMAMMASXSXMMXMMMSMSAMXAXSAAAAMXSASMMAMAMXXAMXMXSMXSAMXMAMXSXMAMMAMMSAM",
                "SSSMAMXSASASMMMXXXAXMMMSMMSMMSMAMAXXXAAAMAXSAXMMMMASAMXMSAXAXSSMMMSAMMAMXMXXAAMMMMAAMAMAMXSMMSMSSMMSAMMSAMXMXMMSSMXMASXAMASAMAMAXAMMMMSXXSXS",
                "AAAXXXXMASMSAMMXSAMXAAAAAAXAAXMASXMASMMSSSMMMXMAAMAXASXXMMMSMXAASXMXSAMXMSMSMAMAASMSSMMMMSXASMAAMAAMXMASXMMXMXMAMAAMASMAXXXMXSMMSMMXAAASAMXM",
                "MMMMSSMMMMXSAMSMSMXMSMXXMMMMMSSXSASXMMXMAXMASAXMSSSSSMMMMASXSXSMMAMXMMMAMAAAXASXMMAMXAAAMASMMMMMSSMSASMSAXMASAMAMMMMASXSASXSAXXXAMMXMMSAXMAS",
                "XSXAAAXXMXAMAMSAXAAAXSSSSSMMSAXAMAMAAAAMMMSAMXSAAAAMMAAMSXSAMMMXXAMAXXXSSMSMSXSMSMAMSSMXSAMXASXMXMASASXMMSSSSXSAMASXMMMMMMAMASMSASAAMXMASXAA",
                "AMMMSSMAXMMSSMMXMMMXMAXAAXASMSMMMSSSMMMXSAMAAAAMMMMMMMMXSAMXMAMASASXSXXMAMXXMXMAMSSMAAAXMASMXMASAMXMXMAXXAXAXMSAMMXAXXAXAMXMXMASMMMMSAMASMXM",
                "MXSAMAXMXAMAXASXSXSXMMMMMMMMAMSXXAAMXMSAMASXMAXMAXAAXAXMSAMXMXSAXXAXAXSXXMSXSAMXMAXMMMMMSAMMMSMMMMXAMXSMMSMMMXSMMSSMMSSSSSXMMMMMMSAMXMMASAMS",
                "SAMASAMMSMMMSMMAXAMAXXXAXMXMXMAMMMMMAXMASAMMMAMSMSMSSXSAMAMMXXMMSASMMMSAAAAASMSSMSSMSMSXMASAAAMASXMAXMAMAAAASXSMAAAAMAMAAXXAAAAAXSXMASMXMMAA",
                "MAXMMMSAXAAAMMMSMMSSMMSSSMASASAXSXSXXMSAMMSMXAXAASAAAMMAMAXMMAAMAXXSAAMSMMMXMAMMAMXAAASXMASMSXSAXSAAASAMMMMMSAXMMSMMMXMSMMMSSSMSMMMAMXMAXMSM",
                "XAMSAMXAMSMMSMAXAMAXAAAAAMASAXXMSASXAAXMXMAMMMSMSMMMSMXASXSMMASMMMAXXSMMMXMAMAMMXMASMSXAMAXMMXMMSSMMMSASXSSMMMMMXAMSXMAAAXXAMMXXMXXAMXMSXAXX",
                "MMXSASMMMXAAAMXSSMAXMMSSMMMMMMAMMAMMMMMMASASAAXMAMAAXMSAXAAMAAMAXXAMXXMXMAXSSMSMAMXXXMXXMSSSMMSMAXAMASMMAMSAAXAXMASXASXSSMMAXXXMAMSASXAXMXMX",
                "ASAMMAAASXMSSSMMMMSSSMXMXXSASMSMMXMXMXXSASASMAMSASMXSASASXXMMSSSMMAMSASXSXSAMMAMAXAAAXSXMAAAXSAMSSSMASAMMMMMMSMSSXMMMMAAXASAMSMXAMXSSMMSAXAM",
                "SMASMMSMAAMAMXAMAMXAMSAMXMMASXMASMMSXAMMXMAMAXXMXSMXAMMAMXAXMXAXAXAMMAMAAXMAMSASMSSXSAMXMMSMMSASMAAMAMMSXSXMMAMAXAMXAMXMXXMAMSAMXSXXXAAXAMMA",
                "XSAMXAXXSSMMMSMMMMMMMSXMASMAMASAMMAMAMMSSMMMXMMSAMXSMXMSMSMMSMMMXMAMMSMMMMSAMMASAMXMMMMSMAMXASMMMSMMSSXSASXXSAMASMSSMMASXXXXMMSMAXMAXMMSMSXS",
                "AMMMMMSAMXAAAAMMMSAMXMASMSMSSMMMMMAMXXAAXAXMASAMMXAMXAAMAMXAXAMAMSAMAXAAAMMAMMAMMAAXXAAMMSSMXSAAXMXMXMAMAMAXSAMXXXAMXSASMMSAMAAMXSMSMMMAAXMM",
                "XMASMAMMMSSMMMSAAMSXXAMXXMAMAAMASXMMMMSXSSMXXMSSXMXSSXSMMMMMSSMSASASASXMXMSSMMSMXMMXSMMSAMAMXSXMMSAMXMAMAMSMMAMAMMMSMMAXAMXAMSSMMMAAAASMSMAA",
                "MSAMXSAMAXXAMAMMXMMSAMXMAMASMMMAAAAAXAMXMASAMXAXMASXXSXMASAMAXAXMSAMXSMXXMAMAAXMMMXMAMXMXSAMXMAMAXXXAXMMSXXASMMXSAAAXMSMXMSXMXMAAMMMSMXAMXXM",
                "MMSSXMAMMSSSMXSAXSAMXSAMASXSMAMMSSMSMSSXSAMXMMMSXSXMMMSSXSMSASXMXMXMMMXMAMASMMSSMASMSMSAASXMASAMXSMMSXSAMXMMAMAAXMXSMXAAMMAAXAMSXMAMAXSMMSMS",
                "SAAMMSAMAXAXSXMXXMASASAMAMAXXAMMMMAAXXAAMAMAASMMMMAMAAXXXMASAMXMXMMMAMAMXSASAAAAMSMAXAAMXSMSXSASXAAAAAMXMAXXAXMMMSAMXAMXAMSMMMXAXMXSAXMXMAAM",
                "MMXSXSAMXMMMMMMMMSMMMSAMSSMSXSMSAMSMSMMMMASAMXAMAMXMAMMXXMAMAXXXAAAXAXXMAMMSMMSXMAMMMMMSAMAMASAMXSMMSSXMMSSSSMSAAAASAMXASXXAAMAMMMAMMMMAMMSM",
                "SAXSXMXSAMAAAAMAAAAMXXAMXXXSMMAMXMAMXXMASXSAMXXMAXMXMSMXXMXSAMSSMSXSASMASMMXXXMXSSSXAXAXAXSMMMMSMMMXAAXMAMXAMAMMSSMMMMSSMMXMMSASAMAMSASXSMXX",
                "MXSXAMAMMSSSSXSMSSSMXSSMSMXSAMAMAMAMSMMXXXMXMASMSMSAAAMMXSAMASXAAMMMMAMXMAMASMMMXAMAMMMSMMXXXXAAAASMSSSMASMMMSMAMMMXAAXAAAMSASAMXSAMMASAAXAX",
                "MMSXMMASXMMAMMAAAXAMAXAAAXAXXMAXMSMMMASXMMSMMMSAAASMMMASAMASXXXSMXXMSSMASAMAXAASXMMSAAMAMAMSMMSXSMSAMAMMAMXMAXMSSMXMMXSMMMSMAMAMMMMSSMMXMMSX",
                "XAXAXXXSAAMAMXXMXSMMSSMMMMSSSSSSXAMASAMASAAASXMXMMMXASXMASAMXMXXAMSXMASXXAMXSSMSAXAAMXSAMMAAAAXXXMMAMAMMMMAMMXAMAMSMSXXAAXXMXMAMAAAXAAAXXXMM",
                "MSSXMASXXMMASXSAMXMAMMAAXXXAXAXXXMSMMASXMMMXMAAMXASMMMAMAXAXXMAMXMMASXMMXSAMXMAXMMMXXMSMSMSSMMSXMAMXMASAXSASMMMMMMSAMASXMMSSSMSSMXMASMMSSMSA",
                "AXAAXXXMAXSASMAMSAMXSSSMMMMXMXMMAMAXMAMAAAMSMMMMSMSMMSAMSMMSMMAXAAMAMAMAAMAXSMXMXAXASMSAXAXXXXMAMSSMSXMAXXXAMXMASAMAMAMAAAXAAAAMXAMAXAXXMAXS",
                "SMSAMXMASMMMMXAMMXXAMMMAAASMMSASMSXSMMMSMMXAAAXXAAXAASXMMAAAASASMXMMMAMMASMMMXMASXXXMAMMMSAMMMSMMAAXSAXSASXSAMXXMMSMMXSSMSMSMMMSSSSMSSMMMSMX",
                "MMAMXSMAMAAXXMXSASMMSAXSMSAAASAMAXAMXMMXXMMSSMXSMXMMMSXMXMMSXMMSAASMSXSMAAMAXMAXXXASMSMXMMAAAAAXMMMMMXMAAAAXXSMXXMAMXMMXAXAXAMXXAMAMXAXXAMMM",
                "MXMSSSXAMSMMAMMSAMXXMXXMMMMMMMAMAMXMXSAMASAXAMXXMSXSAMAXSAAMASAMXMAAXAXMMSSMMMMXMMXMAXAMXSSMMSMSMSAXXASMSMAMAAXMMSMSAASMAMSMASAMXXXMSMXMMSAA",
                "SAMXAMSSXMSMAXAMMMSXMSXSAXAAXSSMMXSAMMAMAMXSMMAAAAXMAXMMAMXSXMSAMXMAMXMXAAAAAXSAMAAMSMSSMMAMMAAAAAAMSMMXMMAMSMAAAMXSMSXAAXASAMMSSXMAXXMXAMAX",
                "SASMXMAXAASMMSSMSAMAMAAAMXSMMAAAAAMAMSSMMSAMXSSXMMXSMMSSMMMMXXXMASXSMAMMMSMMMXMASXXXAMXAXMAMSMSMSMSMSAMAXSXMASAMXXASXMMSMSMSXMMAXAMAXMAMSSSX",
                "SAMXAMASXMMAMXMAMMXAMMMMXAMXMSSMMXSSMAAAAMASXMMSAXXXMAAAXXAXXAMMMMMXSAXAAMXSMSSMMMSASXMXMXMXMXAXXXAASMMMXMAMXAMXSAMSAXAAMMAMXSMSSXMASASXXAXM",
                "MMMSMXAAAMSAMMMAMSMSSSMMMMSAXAMXMXSAMSSMMSSMMAASXXAAMMSSMSXSMXMXAAMMSXSXSMASAXXAAASAMXMSSXMAMXMASMMMMXXMAXXMMXSAXAMSMMSSMMAMXAAAAAXAXMMXMMMA",
                "AMAMAMSSMMAMMXSSXSAXAMXAAAXMMASMMMSAMAAAAXAASMMSSMSSMAXAAXAXXASMSMSASMSAAMAMMMSSMMXAXXMAMMSMSAMAMASXMAXSSMMSMAMXSMMXXAXMASMSMMMMXSMSSMMAMMAX",
                "XMAMXXMAAXXXMAMMAMXMASXMSSSMSASAAASXMSSMMSMMMMMXMXAMMXSMXMMMMXSAAXMXXAMXMMXXAMAMXXMSMSMAXMAASAMAXSMMMSXMAASXMASMMAASASMSMMAAAXASXMAMAASXSSMS",
                "MSSMMASMMMMMMAXMMMSXXMAMAAAAMASMSMSMMXAMAXXAXMSAMMMSSMMMAAAXXXMXMMSMMSMSMMAMMMMSSXMMAASMMMMXSXMSXXMSAMAMSMMASXSAMXMSAMAAMSSMSMAMXSSMSMMAAAMX",
                "XAAASMMXAAASMSSMAAMAMSSMMSMMMXMAMAMAXXAMMSSXSAMASAAAMAASXSMSSMMAXAAAMXAAAMSSMAAAMAMMXMSXMSXASMMMAMAMASMMMASXMASMMXXMAMSXMAAXXMXSMXAAXXXMSMMM",
                "MMSMMAMSMSMSAXAXMSSMMAXAXXMXSAMAMAMSAXMMMXAMXASXMMMSSSMSXXMAAMSMMSSSMMMMMMAAMMMMXAMAMSMMMSMMMAAMMMAMASXMMAMASXSAXXASXMXMMSSMXMXMAXMMMXXXMAXX",
                "MAXAXXMAAMXSMSMMMXXMXXXMMMSASASXSMXMMASAMXMASMMMMAMXXMASMSMXSXXXAXXAAMXAMXSMMXAXSMSASAAAXXSMXSMMAMXSXMAXMAMXMASAASMMMAMXAAMMSSMMMMAAXXXASMMS",
                "MSSMMSMMSMAMMAAAXXXMASASXMMASAMASMXSXMSASASXXMMASAMXAMXMAAXSAXMMSMMSMMSSSMXSASXXAASXMMSMSSXSAAMSSSMSMSXMMMSMSXMMMSAASXSMMMSAAAAAXSSMSSMMMAAM",
                "XMAXAAASAMMSMSXMMMASASAMXAMAMAMAMXXMAMMMMAMMAMXMXMSSMMAMSMSXAAMMASXMMAXAAAMSXAXSMXMASAXXXXAMSSMAMAAMASMSMAAAXXAXASAMAAAMSSMMSSMMXMAMAXAASMMX",
                "XSAMXSMSASAAAMSMXSAMXSXMXSMSSSMXXAMSXMASMAMSSMSXSAMXAAAMAXXMMMXSAXMAMXSSMMMSXMASXAMXAASMMMMMMXMMSMMMMMAAMMMSMMXMASMSMAMXMASAXAAXAXAMXSMXSXSX",
                "MMMSAMASXMMSXSAMXMASXMMSAXXMAXAMMMAAASASMSMMXAAAAXXSMSMSMSMAMSAMXXSAMXMXAMAXAXMMMXMAMSMAAAAAXMXMXXXAMMSMSMMXMMAMXMAXXXMASMMMSSMMMSXSASXMMAXS",
                "MAASASAMAMAMMSAMXXAMXAAMASAMMMMMAMXSMMASMMAMMMMSMMAXAAAAAAMAMMASAXMASXMASMMSASASMSMAXAXSMXXMMXMMMMSMSAMMAASXMSMXAMSMMMSASXAMXMASXAXMAMASMMMX",
                "SMMSMMAXXMAXAMMXSMMSSMMSXXAMXASXMSAXMSXSASMMAXXMASXMSMSMSMSSMSAMXSSMMAXAMXXAASAMAAXAMSXMASXSSMSMAAAXMASMSSMAAXAASXMAMAMASMXXXMAXSSXXAMAMAXAA",
                "ASAMXSXMMSMSMAMAMXAAAXXXXSXMSXSAAMAMAMASAMXSSSXSAMMXMAAXAMXMMMMSMXAASXMMMMSMMMXMSMMXAMAMAMAASAAMSSMMMAMXMAXMMMMMMASXMAMAMMSXXMSXXMAMSSXSMMSA",
                "AMMXMASAAAXAXAMMSSMSSMMSMSMASAMMMMAMXMAMAMMAMXAMAMXAMSMXMMXMXAMAMXMMMXAMAAXXXAXAAAXSXMAMAMMMMSMXMAMSSMMASMMMXAXASXMXSASAAXAMXAXSMXSAMXASXMAM",
                "SXMMSXAMSSSSSXSAMAAAMXAAAMMAMAMMSSSSSMMSAMMSAMXSAMSAXMAMXMAMXMSASXMSSMSSMSMSXMMSMAMSASMSSSMMMMXAMAMMAMSASAAXMXMAXAAAXASMSMMAASMXMAXAAMAMAXMM",
                "XAMAMXMAXXMAMMMASMMMSSSMSMMXSXMMMAAMXAASAMAMXMXSAMMMAMXAAMASAAMASAAAAAAAAAXSASMAMAAXAMAAAAXMASMSSSMMAMMXSMMXAAAMSMMAMXMAMAXSSMXAMXSASMAXSMMX",
                "SMMASMXMXXMMMASAMXSAAAXAMXMXSXSAMMMMSMMSXMASAAMSXMMSAMMSXSASMSMASMMMXSMMMMMSAMSXMXSMSMMMSSMMASAXAAASMMSXMAXMSXMXAXSXSMMXMXMMAMSXSAMMXMSAMASM",
                "AXMAXAAMSMSXSASXSXAMMSMMMASMSASXMSAXXMASASASMSAMAMAMASXMXMAXMXMASXASAXMSXMAMXMAXMSXMMAMAMAMAXMXMMMMMSAMXSMMAXXSMMMAAAAXMASMSAMMAMXMSAAXMSXMA",
                "MSMSXXAMAAMAMASAMMMMAXAAXXSAMXMAMSASMXASAMASAXMXAMMXXMXMMMMSSMMXXMASMSAAAMSMXMAXSAAMXSMMXAMAMXMXSAXXMXMAAXAMSAMASXMXMSMMAXASXMMASMAMMSSXMASM",
                "XXAMASXSMXMAMMMMMAXMSSMMSSMXMMXMXXXMMMXSMMMMMMSSMSXAXSAMXAXXAASXSMAMXMMMSMMAXAMXXAXMAXAXSAMSAMXAXXSXMASXMASXMAMAMAXSSMXASMMMAXSAMXXXSMMAXAMA",
                "SMAMAMAAXASXSAAASMSMMAASXMAAXAAMMMMSXSMXXAXAXMXAMSMMSAAMSMSSSMMAXMAMXMMXXAMMMMMMMSMMXSAMSXMASAMMSMAMAMXSMXXAMAMAXXMMAAMMXAAMAMMASXXXMAMSMXSM",
                "AAAMAMMMMMXAMMXMSXMASXMSAMSMSSMSAAXAAXMASMMSXXSAMXAMAXMMMAMAXMMMMSMSSMSXMAMAAXXAAAAXAMAMXASAMMMMAXXSXMAAMAMASMSMSMMSMMMXSMMMSSSXMXMMMSMAXMAX",
                "SSMSXXAAAXMMMSSMMXSAMXAXXMAMAMASXSMMSMMXMMMXMMSMMMXMAXXXMAMXMMXMAMMAAMAASXMSMSAMSMMMXMASMXMASASMMMASAMXAMXSAMMAXAMXXAXXXMMAXMXMXAMXSAMXAMMXM",
                "MAMXASMMMXMMAAAMAMMASMMMSSMMAMMMXXAMXAXAXAASAAXAXAXMMSSMMMSMAXAMXSMSSMSXMAXAMXAMAXMSMSASAMXAMXMAASMSXMSXMXMASXSSMSSSMMXMASMMSAMMXMAXASMSSSMM",
                "SAMMXMAASAMXMSXMAMSAMXAAXASMMMXMAXASMSMAMMSSMMXXMMAXAAMAAAAAMSMSXAAAMMXSAMXAXXAMXSMAAMAXMAMXSAMMMMAXAMXAAXSSMAXAXAAAXAXMAMXAMAMASMXMAMAAAMAX",
                "SAMXXXMASAXMXXASAXXMASMMSMMMSSSMMSAMAMAXMSAMASXMMSSMMSSSMMSSXAAMXMMMSXSAMXSSMSSMAXMMMMXMXMSASXXMAAMSAMMSAMXXMSSMMSMMMSXMASMSSSMAMAXMMMMMSMMM",
                "XAXSAMXMSXMSASAMXSAMAXAAXXAAMXAAAMXMAMXXXXASAMXAXAAAMAMXSXAXXMMXAMXMAMXMAMXXAAAMXSSXMXAMAXMXSAXSAMXMAXAXASMSAMXXAXASXMAMXMAXXASXMSAMXAAAAAXA",
                "MSMMASXMSMXMASAMXXAMXMMMXSMSSXMMXMMSASMMMSXMAXMSMSSMMMSAMMMMXSASXSSMSMSXMXXMMMSAMXXAMSASMXMXMXMAAMASMMXSMAAMASAMSSMSASMMSMMMMMAXAXASASMMXSXX",
                "MXAXAMAMMSAMXMASXSSMMSASAXMAMXSXMMAMAMAAAXMXSXAAAXAXAAMASMXSXMASAAAAAAMXXMMXAAAAMASMMMASAASXMMASMMMAAMXMMAXMASAMXXASAMMAAAAAAXMMAMAMAAXXSMMX",
                "SMXMXMXAASMSAMXSXSAAXSAMXSMSMXSASMASASXMXSXAMMSMSMMSMXSAMAASAMXMMMMSMSMMAMXAMMSAMASXXXAMXMSAMAMMXXMXAMXMMSSMXSAMMMMMAXMXSSMMXXXMASAMXMAXAAXX",
                "AASXMAMXMSASMMAXMXMMMMMMMMAAAAMAMMAXXSXMSMMASAMAAAXAAXMMSMAMXSAAAXXMXMMSASXSSXMAMSSXXMASAMSAMSMSMMXSMSXSAAAXAMAAXAXMAMSMMMMSMMXSASMXMXMSMSMX",
                "MSMAASMSMMAMAMASAAXXXAAAMMSMSXMMMMMXMSAMAASAMMSSSSMMSMMAXXAMXSXSMSAMAXXSMMMAMXXAMXMXMSAXXMXAMMAAAMMAMXAMMSSMSSXMSXXMSMMAMMAAAAXMASXXAAXAMXAX",
                "XAMXMMAXSMXSMMXAXMSMSMSXSXAAAASAMXMAMXASXMMASAAMAAXAMAMSSSMSAMXXASMMASAMXMMSMMSMSXMAMMSSSSSMMMSMSMAAXMXMXXMAXAXXXXXXMASMMMSSXMXMASMSSSSMMMSX",
                "MMAXMMXMXSAMXMXMXMAAMAMASMMSMXSASASMSMMMMXSXMMSSSXMXSSMMAMXMMSASMMSMAMASXASAMAAAAXSAMSAXMAXAAAXXMMSMMSSMMSSSMSMSASMXSAMASXAXAMXMXMAXAXAAAAMM",
                "AXSAMAXMMMMSAMMXASMMSAMAMAXAMMSAMASAAXSSSMXAMXMAMMSMAAXMXMXXXMMSAMXMSSXMMMSASMMSSXSXSAMXMAMMMMMXXAAAXXAAAAAAAXAMXMAASASAMMAXMXMASMSMMMSMMMSA",
                "SMAASXSMAAASMMAMXSAAMAMMMXMMXAMXMMMXMASAAXSSMSXAAASASMMSSSMMSAMXMMXXXXAMAXSAMXMAMAMMSMXXMSXSASAAMSSSMSSMMMSMMMSMXMMMSXMAMMMMSAXAXMXMAAXAMAMX",
                "XAMXMAAASXXSASMSAMMMSXSMMXMXMMMMSAMXXSXSMMSAAMXMMASAMXXAAAXXAAASMSXXMSMMSMMMSMMMSXMASXXXMAAMAMMSMAAAMAMAMMMAXXAXSXMMMMSSXXMASASXSMASMSSXMAMX",
                "MSSMMSMMMMXSAMAMAXAAAASAAASASMSASASMMMAMXXXMMMXMMXMAMAMMSMMSSSMSAMXXMAMAXMAXMAXMXMMXSMSSMMSMAMAXMMSMMASMMAMSMSMSXMSAAMAMMSSMMXMAAMAXMMMMSMSM",
                "AXAAAMASXXAMAMXMXAMSMXMMSXSASAAXSXXAAXAMSAMXAAAXAASMMAAXMAXAAAAMMMXMMAMASMSMSAMSAMXAMXAMAAXMXMASXAXXSMSASASAAAMXXASMSMMSAAAXSAMSMMSXSAAAAAAA",
                "XSSMMSAMXMXSXMASXXXXXMAXXMMXMMMAXMSSMSASXSASXSSSSMXSSSSMSSMMSMMMAXMASXSMSAMXMXMSAXMASMSSMMSAMXXXMSMMAMXMSSSMSMSMXXMSXMXMMSSMSMMMSAMXSSSSMSMS"
        );

        int count = 0;

        for (int row = 0; row < input.size(); row++) {
            for (int col = 0; col < input.getFirst().length(); col++) {
                if (input.get(row).charAt(col) == 'A') {
                    count += checkForXMAS(col, row, input);
                }
            }
        }


        System.out.println(count);
    }

    private static int checkForXMAS(int col, int row, List<String> input) {
        int count = 0;
        if (row + 1 < input.size() && row - 1 >= 0 && col + 1 < input.get(row).length() && col - 1 >= 0) {
            String xmas = "" + input.get(row - 1).charAt(col - 1) + input.get(row).charAt(col) + input.get(row + 1).charAt(col + 1);
            if (xmas.equals("MAS")) {
                count++;
            } else {
                xmas = "" + input.get(row + 1).charAt(col + 1) + input.get(row).charAt(col) + input.get(row - 1).charAt(col - 1);
                if (xmas.equals("MAS")) {
                    count++;
                }
            }
            xmas = "" + input.get(row - 1).charAt(col + 1) + input.get(row).charAt(col) + input.get(row + 1).charAt(col - 1);
            if (xmas.equals("MAS")) {
                count++;
            } else {
                xmas = "" + input.get(row + 1).charAt(col - 1) + input.get(row).charAt(col) + input.get(row - 1).charAt(col + 1);
                if (xmas.equals("MAS")) {
                    count++;
                }
            }
        }
        if (count == 2) {
            return 1;
        }
        return 0;
    }

}
